import { isArray } from '@vue/shared'
import type { VNode } from '../vnode'

// #6651 res can be undefined in SSR in string push mode
// #6651 在 SSR 字符串推送模式下，res 可能是 undefined
type SSRSlot = (...args: any[]) => VNode[] | undefined

interface CompiledSlotDescriptor {
  name: string
  fn: SSRSlot
  key?: string
}

/**
 * Compiler runtime helper for creating dynamic slots object
 * 编译器运行时助手，用于创建动态插槽对象
 * @private
 */
export function createSlots(
  slots: Record<string, SSRSlot>,
  dynamicSlots: (
    | CompiledSlotDescriptor
    | CompiledSlotDescriptor[]
    | undefined
  )[],
): Record<string, SSRSlot> {
  // 遍历动态插槽描述符数组
  for (let i = 0; i < dynamicSlots.length; i++) {
    const slot = dynamicSlots[i]
    // array of dynamic slot generated by <template v-for="..." #[...]>
    // 由 <template v-for="..." #[...]> 生成的动态插槽数组
    if (isArray(slot)) {
      // 如果是数组，遍历并将其添加到 slots 对象中
      for (let j = 0; j < slot.length; j++) {
        slots[slot[j].name] = slot[j].fn
      }
    } else if (slot) {
      // conditional single slot generated by <template v-if="..." #foo>
      // 由 <template v-if="..." #foo> 生成的条件单插槽
      // 如果存在 key，则需要包装函数以附加 key
      slots[slot.name] = slot.key
        ? (...args: any[]) => {
            const res = slot.fn(...args)
            // attach branch key so each conditional branch is considered a
            // different fragment
            // 附加分支 key，以便每个条件分支都被视为不同的片段
            if (res) (res as any).key = slot.key
            return res
          }
        : slot.fn
    }
  }
  return slots
}
