import {
  type ComponentInternalInstance,
  getCurrentInstance,
} from '../component'
import { warn } from '../warning'

/**
 * Generate a unique ID for accessibility attributes.
 * 生成用于无障碍属性的唯一 ID。
 */
export function useId(): string {
  const i = getCurrentInstance()
  if (i) {
    // The ID is generated by combining the prefix, the current component's ID base,
    // and a sequence number that increments for each call within the component.
    // ID 由前缀、当前组件的 ID 基础值以及组件内每次调用递增的序列号组合而成。
    return (i.appContext.config.idPrefix || 'v') + '-' + i.ids[0] + i.ids[1]++
  } else if (__DEV__) {
    warn(
      `useId() is called when there is no active component ` +
        `instance to be associated with.`,
    )
  }
  return ''
}

/**
 * There are 3 types of async boundaries:
 * 有 3 种类型的异步边界：
 * - async components
 * - 异步组件
 * - components with async setup()
 * - 带有 async setup() 的组件
 * - components with serverPrefetch
 * - 带有 serverPrefetch 的组件
 */
export function markAsyncBoundary(instance: ComponentInternalInstance): void {
  // Update the ID generation state for the async boundary.
  // We append the current async count to the base ID and reset counters.
  // 更新异步边界的 ID 生成状态。
  // 我们将当前异步计数追加到基础 ID 并重置计数器。
  // instance.ids structure: [baseId, callCount, asyncCount]
  // instance.ids 结构：[基础ID, 调用计数, 异步计数]
  instance.ids = [instance.ids[0] + instance.ids[2]++ + '-', 0, 0]
}
