import type { ComponentInternalInstance } from './component'
import { devtoolsComponentUpdated } from './devtools'
import { setBlockTracking } from './vnode'

/**
 * mark the current rendering instance for asset resolution (e.g.
 * resolveComponent, resolveDirective) during render
 * 标记当前渲染实例，用于在渲染期间进行资源解析（例如 resolveComponent, resolveDirective）
 */
export let currentRenderingInstance: ComponentInternalInstance | null = null
export let currentScopeId: string | null = null

/**
 * Note: rendering calls maybe nested. The function returns the parent rendering
 * instance if present, which should be restored after the render is done:
 * 注意：渲染调用可能是嵌套的。该函数返回父级渲染实例（如果存在），
 * 应在渲染完成后恢复该实例：
 *
 * ```js
 * const prev = setCurrentRenderingInstance(i)
 * // ...render
 * setCurrentRenderingInstance(prev)
 * ```
 */
export function setCurrentRenderingInstance(
  instance: ComponentInternalInstance | null,
): ComponentInternalInstance | null {
  const prev = currentRenderingInstance
  currentRenderingInstance = instance
  // 设置当前作用域 ID，优先使用 __scopeId
  currentScopeId = (instance && instance.type.__scopeId) || null
  // v2 pre-compiled components uses _scopeId instead of __scopeId
  // v2 预编译组件使用 _scopeId 代替 __scopeId
  if (__COMPAT__ && !currentScopeId) {
    currentScopeId = (instance && (instance.type as any)._scopeId) || null
  }
  return prev
}

/**
 * Set scope id when creating hoisted vnodes.
 * @private compiler helper
 * 在创建提升的 vnodes 时设置作用域 ID。
 * @private 编译器辅助函数
 */
export function pushScopeId(id: string | null): void {
  currentScopeId = id
}

/**
 * Technically we no longer need this after 3.0.8 but we need to keep the same
 * API for backwards compat w/ code generated by compilers.
 * @private
 * 从技术上讲，在 3.0.8 之后我们不再需要这个，但我们需要保持相同的 API，
 * 以便与编译器生成的代码向后兼容。
 * @private
 */
export function popScopeId(): void {
  currentScopeId = null
}

/**
 * Only for backwards compat
 * @private
 * 仅用于向后兼容
 * @private
 */
export const withScopeId = (_id: string): typeof withCtx => withCtx

export type ContextualRenderFn = {
  (...args: any[]): any
  _n: boolean /* already normalized (已经标准化) */
  _c: boolean /* compiled (已编译) */
  _d: boolean /* disableTracking (禁用跟踪) */
  _ns: boolean /* nonScoped (非作用域插槽) */
}

/**
 * Wrap a slot function to memoize current rendering instance
 * @private compiler helper
 * 包装一个插槽函数以记忆当前渲染实例
 * @private 编译器辅助函数
 */
export function withCtx(
  fn: Function,
  ctx: ComponentInternalInstance | null = currentRenderingInstance,
  isNonScopedSlot?: boolean, // __COMPAT__ only
): Function {
  if (!ctx) return fn

  // already normalized
  // 已经标准化
  if ((fn as ContextualRenderFn)._n) {
    return fn
  }

  const renderFnWithContext: ContextualRenderFn = (...args: any[]) => {
    // If a user calls a compiled slot inside a template expression (#1745), it
    // can mess up block tracking, so by default we disable block tracking and
    // force bail out when invoking a compiled slot (indicated by the ._d flag).
    // This isn't necessary if rendering a compiled `<slot>`, so we flip the
    // ._d flag off when invoking the wrapped fn inside `renderSlot`.
    // 如果用户在模板表达式中调用编译后的插槽（#1745），
    // 可能会打乱块跟踪（block tracking），因此默认情况下，我们在调用编译后的插槽时
    // 禁用块跟踪并强制退出（由 ._d 标志指示）。
    // 如果渲染编译后的 `<slot>`，则不需要这样做，因此我们在 `renderSlot` 内部调用包装函数时
    // 会关闭 ._d 标志。
    if (renderFnWithContext._d) {
      setBlockTracking(-1)
    }
    // 切换到闭包中保存的上下文实例
    const prevInstance = setCurrentRenderingInstance(ctx)
    let res
    try {
      res = fn(...args)
    } finally {
      // 恢复之前的渲染实例
      setCurrentRenderingInstance(prevInstance)
      if (renderFnWithContext._d) {
        setBlockTracking(1)
      }
    }

    if (__DEV__ || __FEATURE_PROD_DEVTOOLS__) {
      devtoolsComponentUpdated(ctx)
    }

    return res
  }

  // mark normalized to avoid duplicated wrapping
  // 标记为已标准化，避免重复包装
  renderFnWithContext._n = true
  // mark this as compiled by default
  // this is used in vnode.ts -> normalizeChildren() to set the slot
  // rendering flag.
  // 默认标记为已编译
  // 这在 vnode.ts -> normalizeChildren() 中用于设置插槽渲染标志。
  renderFnWithContext._c = true
  // disable block tracking by default
  // 默认禁用块跟踪
  renderFnWithContext._d = true
  // compat build only flag to distinguish scoped slots from non-scoped ones
  // 仅兼容构建标志，用于区分作用域插槽和非作用域插槽
  if (__COMPAT__ && isNonScopedSlot) {
    renderFnWithContext._ns = true
  }
  return renderFnWithContext
}
